version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: django
    image: django
    restart: on-failure:10
    command: /start
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.development
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: on-failure:10

  postgres:
    container_name: postgres
    image: postgres:12.0-alpine 
    restart: on-failure:10
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/      
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

volumes:
  postgres_data: